### ISSUE TITLE
因可爱猫 或 iHttp 插件原因造成无法解决的问题

### ISSUE THREAD

**Issue by 0honus0** [0honus0/efb-wechat-cutecat-slave#11]
1. 群成员修改群内昵称，efb端无法实时更新
2. 面对面收款成功之后发送两次通知，因为iHttp插件发送两次通知
3. 除text消息的emoji正常显示，其余类型的消息中的表情都显示为问号
4. 存在漏收消息的情况，可爱猫无对应消息日志
5. 可爱猫极个别信息接收会有较大延时(微信前置可解决)

**Comment by 0honus0** [comment]
2. 面对面收款成功之后发送两次通知，因为iHttp插件发送两次通知

**Comment by phoenixxie0** [comment]
使用定时更新方式，利用GetGroupMemberList和GetGroupMemberInfo来定时更新？在配置文件加入定时更新选项和间隔时间？

**Comment by 0honus0** [comment]
> 使用定时更新方式，利用GetGroupMemberList和GetGroupMemberInfo来定时更新？在配置文件加入定时更新选项和间隔时间？

问题不在于定时，而是更改之后通过插件获取的信息还是修改前的，并且现在的ttl设置的就是1小时

**Comment by phoenixxie0** [comment]
如果重启可爱猫的ihttp插件，会获取到最新的信息么？

**Comment by 0honus0** [comment]
> 

没尝试 ，但也不能这么做吧
插件重启比较慢，可能漏收消息

**Comment by phoenixxie0** [comment]
利用GetGroupMemberList和GetGroupMemberInfo的时候，加入"is_refresh": 1试试看，这样应该是强制不适用缓存的

**Comment by 0honus0** [comment]
> 利用GetGroupMemberList和GetGroupMemberInfo的时候，加入"is_refresh": 1试试看，这样应该是强制不适用缓存的

文档提示不建议，微信群里面也见有人反馈不生效，所以未尝试，你想试的话，可以自己fork代码改一下

**Comment by phoenixxie0** [comment]
> > 利用GetGroupMemberList和GetGroupMemberInfo的时候，加入"is_refresh": 1试试看，这样应该是强制不适用缓存的
> 
> 文档提示不建议，微信群里面也见有人反馈不生效，所以未尝试，你想试的话，可以自己fork代码改一下

我似乎也没有这方面需求。EMM

**Comment by 0honus0** [comment]
> > > 利用GetGroupMemberList和GetGroupMemberInfo的时候，加入"is_refresh": 1试试看，这样应该是强制不适用缓存的
> > 
> > 
> > 文档提示不建议，微信群里面也见有人反馈不生效，所以未尝试，你想试的话，可以自己fork代码改一下
> 
> 我似乎也没有这方面需求。EMM

插件群里面群主说这个参数可能没用，所以我也没尝试，并且修改群昵称日志无任何提示

**Comment by QQ-War** [comment]
问题4算是解决了吧。

**Comment by 0honus0** [comment]
> 问题4算是解决了吧。

已修改
