### ISSUE TITLE
TG的动图表情似乎无法正常发送

### ISSUE THREAD

**Issue by phoenixxie0** [0honus0/efb-wechat-cutecat-slave#17]
TG的动图表情似乎无法正常发送，tg返回如下
`'Message is not sent.'`
`'UnidentifiedImageError('cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7fe45c6d3eb0>')'`

`'Unknown error has occurred while trying to process this message. See log for details.
UnidentifiedImageError('cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7fe45c6d33d0>')'`

efb端返回如下：
`'Processing Update: {'message': {'supergroup_chat_created': False, 'chat': {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨 AAA', 'id': -1001780126227}, 'new_chat_members': [], 'caption_entities': [], 'message_id': 326, 'channel_chat_created': False, 'sticker': {'set_name': 'Capoo_Video2', 'is_animated': False, 'is_video': True, 'file_unique_id': 'AgADCQYAAuOu4Vc', 'emoji': '🧊', 'file_size': 260027, 'width': 512, 'height': 512, 'thumb': {'file_unique_id': 'AQADCQYAAuOu4Vdy', 'file_size': 25316, 'height': 320, 'width': 320, 'file_id': 'AAMCBQADHQJqGpITAAIBRmJbwB3KRCIzrtMFaqBToUjpGIASAAIJBgAC467hV6RckGCiiyAVAQAHbQADJAQ'}, 'file_id': 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE'}, 'entities': [], 'date': 1650180125, 'delete_chat_photo': False, 'new_chat_photo': [], 'group_chat_created': False, 'photo': [], 'from': {'language_code': 'zh-hans', 'is_bot': False, 'id': ***************, 'username': '**************', 'first_name': '**************'}}, 'update_id': 609393716}
2022-04-17 09:22:05,814 [DEBUG]: efb_telegram_master.locale_handler (locale_handler.check_update; locale_handler.py:44)
    [609393716] Update has language zh-hans.
2022-04-17 09:22:05,815 [INFO]: efb_telegram_master.locale_handler (locale_handler.check_update; locale_handler.py:54)
    Updating locale to zh
2022-04-17 09:22:05,817 [DEBUG]: efb_telegram_master.master_message (master_message.msg; master_message.py:141)
    [-1001780126227.326] Received message from Telegram: {'supergroup_chat_created': False, 'chat': {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨 AAA', 'id': -1001780126227}, 'new_chat_members': [], 'caption_entities': [], 'message_id': 326, 'channel_chat_created': False, 'sticker': {'set_name': 'Capoo_Video2', 'is_animated': False, 'is_video': True, 'file_unique_id': 'AgADCQYAAuOu4Vc', 'emoji': '🧊', 'file_size': 260027, 'width': 512, 'height': 512, 'thumb': {'file_unique_id': 'AQADCQYAAuOu4Vdy', 'file_size': 25316, 'height': 320, 'width': 320, 'file_id': 'AAMCBQADHQJqGpITAAIBRmJbwB3KRCIzrtMFaqBToUjpGIASAAIJBgAC467hV6RckGCiiyAVAQAHbQADJAQ'}, 'file_id': 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE'}, 'entities': [], 'date': 1650180125, 'delete_chat_photo': False, 'new_chat_photo': [], 'group_chat_created': False, 'photo': [], 'from': {'language_code': 'zh-hans', 'is_bot': False, 'id': *************, 'username': '******************', 'first_name': '*******************'}}
2022-04-17 09:22:05,819 [DEBUG]: peewee (peewee.execute_sql; peewee.py:3165)
    ('SELECT "t1"."slave_uid", "t1"."master_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."master_uid" = ?)', ['blueset.telegram -1001780126227'])
2022-04-17 09:22:05,821 [DEBUG]: efb_telegram_master.master_message (master_message.msg; master_message.py:162)
    [-1001780126227.326] Chat {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨 AAA', 'id': -1001780126227} is singly-linked to honus.CuteCatiHttp wxid_6d8qczmsm5nr22
2022-04-17 09:22:05,823 [DEBUG]: efb_telegram_master.master_message (master_message.msg; master_message.py:186)
    [-1001780126227.326] Destination chat = honus.CuteCatiHttp wxid_6d8qczmsm5nr22
2022-04-17 09:22:05,823 [DEBUG]: efb_telegram_master.master_message (master_message.process_telegram_message; master_message.py:253)
    [-1001780126227.326] EFB message type: TGMsgType.Sticker
2022-04-17 09:22:05,824 [DEBUG]: efb_telegram_master.master_message (master_message.process_telegram_message; master_message.py:270)
    [-1001780126227.326] Message type from Telegram: TGMsgType.Sticker
2022-04-17 09:22:05,824 [DEBUG]: telegram.bot (bot.decorator; bot.py:129)
    Entering: get_file
2022-04-17 09:22:07,247 [DEBUG]: telegram.bot (bot.decorator; bot.py:131)
    {'file_unique_id': 'AgADCQYAAuOu4Vc', 'file_size': 260027, 'file_path': 'https://api.telegram.org/file/bot*************/stickers/file_893.webm', 'file_id': 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE'}
2022-04-17 09:22:07,248 [DEBUG]: telegram.bot (bot.decorator; bot.py:132)
    Exiting: get_file
2022-04-17 09:22:08,366 [DEBUG]: telegram.bot (bot.decorator; bot.py:129)
    Entering: send_message
2022-04-17 09:22:08,883 [DEBUG]: telegram.bot (bot.decorator; bot.py:131)
    {'supergroup_chat_created': False, 'chat': {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨 AAA', 'id': -1001780126227}, 'new_chat_members': [], 'caption_entities': [], 'message_id': 327, 'channel_chat_created': False, 'entities': [], 'date': 1650180128, 'text': "Message is not sent.\n\nUnidentifiedImageError('cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7fa7fc233760>')", 'reply_to_message': {'supergroup_chat_created': False, 'chat': {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨AAA', 'id': -1001780126227}, 'new_chat_members': [], 'caption_entities': [], 'message_id': 326, 'channel_chat_created': False, 'sticker': {'set_name': 'Capoo_Video2', 'is_animated': False, 'is_video': True, 'file_unique_id': 'AgADCQYAAuOu4Vc', 'emoji': '🧊', 'file_size': 260027, 'width': 512, 'height': 512, 'thumb': {'file_unique_id': 'AQADCQYAAuOu4Vdy', 'file_size': 25316, 'height': 320, 'width': 320, 'file_id': 'AAMCBQADHQJqGpITAAIBRmJbwB3KRCIzrtMFaqBToUjpGIASAAIJBgAC467hV6RckGCiiyAVAQAHbQADJAQ'}, 'file_id': 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE'}, 'entities': [], 'date': 1650180125, 'delete_chat_photo': False, 'new_chat_photo': [], 'group_chat_created': False, 'photo': [], 'from': {'language_code': 'zh-hans', 'is_bot': False, 'id': ****************, 'username': '****************', 'first_name': '****************'}}, 'delete_chat_photo': False, 'new_chat_photo': [], 'group_chat_created': False, 'photo': [], 'from': {'is_bot': True, 'id': *******, 'username': 'ews_wechat_bot', 'first_name': 'EWS_WeChat'}}
2022-04-17 09:22:08,885 [DEBUG]: telegram.bot (bot.decorator; bot.py:132)
    Exiting: send_message
2022-04-17 09:22:08,885 [ERROR]: efb_telegram_master.master_message (master_message.process_telegram_message; master_message.py:411)
    Message is not sent. (update: {'message': {'supergroup_chat_created': False, 'chat': {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨 AAA', 'id': -1001780126227}, 'new_chat_members': [], 'caption_entities': [], 'message_id': 326, 'channel_chat_created': False, 'sticker': {'set_name': 'Capoo_Video2', 'is_animated': False, 'is_video': True, 'file_unique_id': 'AgADCQYAAuOu4Vc', 'emoji': '🧊', 'file_size': 260027, 'width': 512, 'height': 512, 'thumb': {'file_unique_id': 'AQADCQYAAuOu4Vdy', 'file_size': 25316, 'height': 320, 'width': 320, 'file_id': 'AAMCBQADHQJqGpITAAIBRmJbwB3KRCIzrtMFaqBToUjpGIASAAIJBgAC467hV6RckGCiiyAVAQAHbQADJAQ'}, 'file_id': 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE'}, 'entities': [], 'date': 1650180125, 'delete_chat_photo': False, 'new_chat_photo': [], 'group_chat_created': False, 'photo': [], 'from': {'language_code': 'zh-hans', 'is_bot': False, 'id': **************, 'username': '***************', 'first_name': '****************'}}, 'update_id': 609393716}, exception: cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7fa7fc233760>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/efb_telegram_master/master_message.py", line 394, in process_telegram_message
    slave_msg = coordinator.send_message(m)
  File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/coordinator.py", line 108, in send_message
    msg.verify()
  File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/message.py", line 519, in verify
    assert hasattr(self.file, "read") or not hasattr(self.file, "close"), \
  File "/usr/local/lib/python3.8/dist-packages/efb_telegram_master/message.py", line 131, in get_file
    self._load_file()
  File "/usr/local/lib/python3.8/dist-packages/efb_telegram_master/message.py", line 103, in _load_file
    Image.open(file).convert("RGBA").save(out_file, 'png')
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7fa7fc233760>
2022-04-17 09:22:08,892 [DEBUG]: efb_telegram_master.db (db.add_or_update_message_log; db.py:384)
    [-1001780126227.326] Received message logging request of -1001780126227.326
2022-04-17 09:22:08,893 [DEBUG]: peewee (peewee.execute_sql; peewee.py:3165)
    ('SELECT "t1"."master_msg_id", "t1"."master_msg_id_alt", "t1"."slave_message_id", "t1"."text", "t1"."slave_origin_uid", "t1"."slave_origin_display_name", "t1"."slave_member_uid", "t1"."slave_member_display_name", "t1"."media_type", "t1"."mime", "t1"."file_id", "t1"."file_unique_id", "t1"."msg_type", "t1"."pickle", "t1"."sent_to", "t1"."time" FROM "msglog" AS "t1" WHERE ("t1"."master_msg_id" = ?) LIMIT ? OFFSET ?', ['-1001780126227.326', 1, 0])
2022-04-17 09:22:08,895 [DEBUG]: efb_telegram_master.db (db.add_or_update_message_log; db.py:401)
    [-1001780126227.326] Message record is not found in database, insert it
2022-04-17 09:22:08,896 [DEBUG]: peewee.sqliteq (sqliteq.execute; sqliteq.py:176)
    received query INSERT INTO "msglog" ("master_msg_id", "master_msg_id_alt", "slave_message_id", "text", "slave_origin_uid", "slave_member_uid", "media_type", "mime", "file_id", "file_unique_id", "msg_type", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2022-04-17 09:22:08,897 [DEBUG]: peewee (peewee.execute_sql; peewee.py:3165)
    ('INSERT INTO "msglog" ("master_msg_id", "master_msg_id_alt", "slave_message_id", "text", "slave_origin_uid", "slave_member_uid", "media_type", "mime", "file_id", "file_unique_id", "msg_type", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', ['-1001780126227.326', None, '-1001780126227.326', '', 'honus.CuteCatiHttp wxid_6d8qczmsm5nr22', 'honus.CuteCatiHttp __self__ wxid_6d8qczmsm5nr22', 'Sticker', 'image/webp', 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE', 'AgADCQYAAuOu4Vc', 'Sticker', 'honus.CuteCatiHttp', datetime.datetime(2022, 4, 17, 9, 22, 8, 895448)])
2022-04-17 09:22:08,900 [DEBUG]: efb_telegram_master.db (db.add_or_update_message_log; db.py:420)
    [-1001780126227.326] Database insert/update outcome: 1
2022-04-17 09:22:08,900 [DEBUG]: telegram.bot (bot.decorator; bot.py:129)
    Entering: get_file
2022-04-17 09:22:09,126 [DEBUG]: telegram.bot (bot.decorator; bot.py:131)
    {'file_unique_id': 'AgADCQYAAuOu4Vc', 'file_size': 260027, 'file_path': 'https://api.telegram.org/file/bot**************************************/stickers/file_893.webm', 'file_id': 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE'}
2022-04-17 09:22:09,126 [DEBUG]: telegram.bot (bot.decorator; bot.py:132)
    Exiting: get_file
2022-04-17 09:22:09,584 [ERROR]: efb_telegram_master.master_message (master_message.message_worker; master_message.py:104)
    Error [UnidentifiedImageError('cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7fa7fc2336d0>')] occurred while processing update {'message': {'supergroup_chat_created': False, 'chat': {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨 AAA', 'id': -1001780126227}, 'new_chat_members': [], 'caption_entities': [], 'message_id': 326, 'channel_chat_created': False, 'sticker': {'set_name': 'Capoo_Video2', 'is_animated': False, 'is_video': True, 'file_unique_id': 'AgADCQYAAuOu4Vc', 'emoji': '🧊', 'file_size': 260027, 'width': 512, 'height': 512, 'thumb': {'file_unique_id': 'AQADCQYAAuOu4Vdy', 'file_size': 25316, 'height': 320, 'width': 320, 'file_id': 'AAMCBQADHQJqGpITAAIBRmJbwB3KRCIzrtMFaqBToUjpGIASAAIJBgAC467hV6RckGCiiyAVAQAHbQADJAQ'}, 'file_id': 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE'}, 'entities': [], 'date': 1650180125, 'delete_chat_photo': False, 'new_chat_photo': [], 'group_chat_created': False, 'photo': [], 'from': {'language_code': 'zh-hans', 'is_bot': False, 'id': *******************, 'username': '************', 'first_name': '*****************'}}, 'update_id': 609393716}.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/efb_telegram_master/master_message.py", line 102, in message_worker
    self.msg(update, context)
  File "/usr/local/lib/python3.8/dist-packages/efb_telegram_master/master_message.py", line 206, in msg
    return self.process_telegram_message(update, context, destination, quote=quote, edited=edited)
  File "/usr/local/lib/python3.8/dist-packages/efb_telegram_master/master_message.py", line 415, in process_telegram_message
    if m.file:
  File "/usr/local/lib/python3.8/dist-packages/efb_telegram_master/message.py", line 131, in get_file
    self._load_file()
  File "/usr/local/lib/python3.8/dist-packages/efb_telegram_master/message.py", line 103, in _load_file
    Image.open(file).convert("RGBA").save(out_file, 'png')
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7fa7fc2336d0>
2022-04-17 09:22:09,587 [DEBUG]: telegram.bot (bot.decorator; bot.py:129)
    Entering: send_message
2022-04-17 09:22:10,015 [DEBUG]: telegram.bot (bot.decorator; bot.py:131)
    {'supergroup_chat_created': False, 'chat': {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨 AAA', 'id': -1001780126227}, 'new_chat_members': [], 'caption_entities': [], 'message_id': 328, 'channel_chat_created': False, 'entities': [], 'date': 1650180129, 'text': "Unknown error has occurred while trying to process this message. See log for details.\n\nUnidentifiedImageError('cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7fa7fc2336d0>')", 'reply_to_message': {'supergroup_chat_created': False, 'chat': {'type': 'supergroup', 'title': '𝙒𝙚𝙘𝙝𝙖𝙩丨 AAA', 'id': -1001780126227}, 'new_chat_members': [], 'caption_entities': [], 'message_id': 326, 'channel_chat_created': False, 'sticker': {'set_name': 'Capoo_Video2', 'is_animated': False, 'is_video': True, 'file_unique_id': 'AgADCQYAAuOu4Vc', 'emoji': '🧊', 'file_size': 260027, 'width': 512, 'height': 512, 'thumb': {'file_unique_id': 'AQADCQYAAuOu4Vdy', 'file_size': 25316, 'height': 320, 'width': 320, 'file_id': 'AAMCBQADHQJqGpITAAIBRmJbwB3KRCIzrtMFaqBToUjpGIASAAIJBgAC467hV6RckGCiiyAVAQAHbQADJAQ'}, 'file_id': 'CAACAgUAAx0CahqSEwACAUZiW8AdykQiM67TBWqgU6FI6RiAEgACCQYAAuOu4VekXJBgoosgFSQE'}, 'entities': [], 'date': 1650180125, 'delete_chat_photo': False, 'new_chat_photo': [], 'group_chat_created': False, 'photo': [], 'from': {'language_code': 'zh-hans', 'is_bot': False, 'id': ******************, 'username': '*************', 'first_name': '**************'}}, 'delete_chat_photo': False, 'new_chat_photo': [], 'group_chat_created': False, 'photo': [], 'from': {'is_bot': True, 'id': ***************, 'username': 'ews_wechat_bot', 'first_name': 'EWS_WeChat'}}
2022-04-17 09:22:10,016 [DEBUG]: telegram.bot (bot.decorator; bot.py:132)
    Exiting: send_message'`

**Comment by 0honus0** [comment]
我这里可以的

**Comment by phoenixxie0** [comment]
非动态的贴纸可以发，但是动态的贴纸就出错，不知道是哪里出了问题。可爱猫端没有收到efb的消息传入。应该是efb端这边的问题

**Comment by 0honus0** [comment]
我这边都可以的，检查下是不是转码失败之类的

**Comment by phoenixxie0** [comment]
进程中并没有发现调用ffmpeg的记录。

**Comment by 0honus0** [comment]
确实不显示ffmpeg记录

**Comment by phoenixxie0** [comment]
测试了不同的几个表情，有一部分能发送，但是会变成gif文件形式发送到对方，并不是动态表情。一部分直接无法发送。

**Comment by 0honus0** [comment]
以发送图片的方式发送gif只会显示一个图片，只能以发送文件的方式发送

**Comment by phoenixxie0** [comment]
PC版本微信好像也是可以发送动图表情的？可爱猫的httpsdk好像可以用SendEmojiMsg来发送动图表情

**Comment by 0honus0** [comment]
可以，但仅限于微信自带或者一些特定格式的gif，具体未测试

**Comment by phoenixxie0** [comment]
增加一个SendEmojiMsg的event会成功么？

**Comment by 0honus0** [comment]
可以尝试一下

**Comment by 0honus0** [comment]
试了下可以，等下更新

**Comment by phoenixxie0** [comment]
可爱猫是不是没有撤回消息的方案，我看SDK里没有写类似的说明

**Comment by 0honus0** [comment]
> 可爱猫是不是没有撤回消息的方案，我看SDK里没有写类似的说明

是的

**Comment by phoenixxie0** [comment]
> 试了下可以，等下更新

日常催更~

**Comment by 0honus0** [comment]
> > 试了下可以，等下更新
> 
> 日常催更~

更新了啊

**Comment by phoenixxie0** [comment]
> > > 试了下可以，等下更新
> > 
> > 
> > 日常催更~
> 
> 更新了啊

不好意思，找到了，之前没细看代码

**Comment by phoenixxie0** [comment]
测试了一下，原来能以gif文件发送的表情，现在已经能够正常使用SendEmojiMsg发送过去变成正常的动态表情。但是原来返回异常的动态表情，现在依然返回之前的错误。我查看日志发现可能是缓存问题，或者是因为表情包的体积过大，超过了限制？是否可以按照EWS的方法返回体积过大 [https://github.com/ehForwarderBot/efb-wechat-slave/blob/master/efb_wechat_slave/__init__.py#L421](https://github.com/ehForwarderBot/efb-wechat-slave/blob/master/efb_wechat_slave/__init__.py#L421)

**Comment by 0honus0** [comment]
> 测试了一下，原来能以gif文件发送的表情，现在已经能够正常使用SendEmojiMsg发送过去变成正常的动态表情。但是原来返回异常的动态表情，现在依然返回之前的错误。我查看日志发现可能是缓存问题，或者是因为表情包的体积过大，超过了限制？是否可以按照EWS的方法返回体积过大 [https://github.com/ehForwarderBot/efb-wechat-slave/blob/master/efb_wechat_slave/**init**.py#L421](url)

也行吧

**Comment by phoenixxie0** [comment]
> > 测试了一下，原来能以gif文件发送的表情，现在已经能够正常使用SendEmojiMsg发送过去变成正常的动态表情。但是原来返回异常的动态表情，现在依然返回之前的错误。我查看日志发现可能是缓存问题，或者是因为表情包的体积过大，超过了限制？是否可以按照EWS的方法返回体积过大 [https://github.com/ehForwarderBot/efb-wechat-slave/blob/master/efb_wechat_slave/**init**.py#L421](url)
> 
> 也行吧

也许还可以设置一个配置参数，如果大于指定大小的表情，则发送第一帧，或者怎样？

**Comment by 0honus0** [comment]
> > > 测试了一下，原来能以gif文件发送的表情，现在已经能够正常使用SendEmojiMsg发送过去变成正常的动态表情。但是原来返回异常的动态表情，现在依然返回之前的错误。我查看日志发现可能是缓存问题，或者是因为表情包的体积过大，超过了限制？是否可以按照EWS的方法返回体积过大 [https://github.com/ehForwarderBot/efb-wechat-slave/blob/master/efb_wechat_slave/**init**.py#L421](url)
> > 
> > 
> > 也行吧
> 
> 也许还可以设置一个配置参数，如果大于指定大小的表情，则发送第一帧，或者怎样？

没有实现思路，看下efw那边对图像又进行了一次转换，不确定这边是否有必要添加这一步

**Comment by phoenixxie0** [comment]
> > > > 测试了一下，原来能以gif文件发送的表情，现在已经能够正常使用SendEmojiMsg发送过去变成正常的动态表情。但是原来返回异常的动态表情，现在依然返回之前的错误。我查看日志发现可能是缓存问题，或者是因为表情包的体积过大，超过了限制？是否可以按照EWS的方法返回体积过大 [https://github.com/ehForwarderBot/efb-wechat-slave/blob/master/efb_wechat_slave/**init**.py#L421](url)
> > > 
> > > 
> > > 也行吧
> > 
> > 
> > 也许还可以设置一个配置参数，如果大于指定大小的表情，则发送第一帧，或者怎样？
> 
> 没有实现思路，看下efw那边对图像又进行了一次转换，不确定这边是否有必要添加这一步

我看了ews那个，有个部分是在判断gif的文件大小。但是没发现判断文件是否可以通过微信发送的逻辑。这边的返回错误，看起来应该是某个地方的缓存问题？我调试也没发现具体的地方。是否可以考虑在调用SendEmojiMsg前进行一次判断，如果日志已经返回错误，则进行转码发送第一帧之类的？
