### ISSUE TITLE
在联系人前加入“#”号，以形成标签，方便查询

### ISSUE THREAD

**Issue by phoenixxie0** [0honus0/efb-wechat-cutecat-slave#31]
是否可以考虑，像源ews端一样，在联系人前加入“#”号，以形成标签，方便查询。

**Comment by 0honus0** [comment]
给个样式

**Comment by phoenixxie0** [comment]
📱👤 NAME:
在NAME前加入#  可以做为标签方便查找，我没找到原来的ews是如何实现的。可能在iChat那边就已经实现了。
另外receive_self_msg: 的设置似乎已经失效了。是否考虑修复一下。如果可以，是否能改为设定为true的时候，如果有绑定到群组，则在对应群组显示？这个好像是没有办法的？我看了ihttp插件发来的消息，没带有正确的from_name。如果无法实现，是否可以当为false的之后，自己发的消息直接过滤。过滤from_name或者from_wxid应该可行。

以下是几个个原ews发来的消息模板：
𝙒𝙚𝙘𝙝𝙖𝙩👤 #微信支付:
🔗 微信支付凭证 (https://wx.tenpay.com/cgi-bin/mmpayweb-bin/jumpuserroll?trans_id=???????)
付款金额￥84.60
支付方式零钱
收单机构财付通支付科技有限公司

𝙒𝙚𝙘𝙝𝙖𝙩👤 #笨笨熊 (Bruce Wayne):
💩

其中笨笨熊是备注，括号内是微信昵称

**Comment by 0honus0** [comment]
receive_self_msg: 的设置没有失效吧

**Comment by phoenixxie0** [comment]
> receive_self_msg: 的设置没有失效吧

我这边设置为False，结果依然会在bot发送过来自己发送的消息

**Comment by 0honus0** [comment]
receive_self_msg: False
我试了下没问题的

**Comment by 0honus0** [comment]
不设置默认就是False，你可以试一下

**Comment by 0honus0** [comment]
label_style: True
配置文件添加这个启用
直接谷歌翻译的，凑合着用吧

**Comment by phoenixxie0** [comment]
> 不设置默认就是False，你可以试一下

无效的，因为有的账号，修改过微信号，它和微信的wxid不是一个东西了，可能一个账号的wxid和微信号不是一个了。
参数1: iHttp|发送数据：{"event":"EventFriendMsg","robot_wxid":"AAAA","robot_name":"Phoenix","type":1,"from_wxid":"xxxxx","from_name":"Phoenix","final_from_wxid":"xxxxx","final_from_name":"Phoenix","to_wxid":"AAAA","msgid":"1177070765","msg":"那画图那种，计算题什么的，怎么考"} | 参数2:  | 参数3:  | 参数4:  | 参数5:  | 参数6:

**Comment by 0honus0** [comment]
不只是通过微信id判断的，是通过EventSendOutMsg事件判断一次，如果设置为False，就不区分wxid了，直接return了

**Comment by phoenixxie0** [comment]
> 不只是通过微信id判断的，是通过EventSendOutMsg事件判断一次，如果设置为False，就不区分wxid了，直接return了

然而，我在手机微信上发送给好友的消息，tg也还是会收到。因为ihttp发送过来的是EventFriendMsg。

**Comment by phoenixxie0** [comment]
> 不只是通过微信id判断的，是通过EventSendOutMsg事件判断一次，如果设置为False，就不区分wxid了，直接return了

看了一下代码的逻辑。robot_wxid和from_wxid。因为可爱猫527获取的这两个值是不一样的，导致ihttp发送的数据也这样。slave这边判断这两个不一样就会发送到tg，感觉还是可爱猫的锅。

**Comment by 0honus0** [comment]
{"event":"EventSendOutMsg","robot_wxid":"wxid_0gojra8******2","robot_name":"","type":1,"from_wxid":"wxid_0gojra8******2","from_name":"","final_from_wxid":"wxid_0gojra8******2","final_from_name":"","to_wxid":"wxid_18wkxl0*****","msgid":"1064114996","msg":"不好搞"} | 参数2:  | 参数3:  | 参数4:  | 参数5:  | 参数6: 

我这边手机端发消息日志是 EventSendOutMsg ， 版本不一致吗？

**Comment by phoenixxie0** [comment]
> {"event":"EventSendOutMsg","robot_wxid":"wxid_0gojra8******2","robot_name":"","type":1,"from_wxid":"wxid_0gojra8******2","from_name":"","final_from_wxid":"wxid_0gojra8*_****2","final_from_name":"","to_wxid":"wxid_18wkxl0****_","msgid":"1064114996","msg":"不好搞"} | 参数2: | 参数3: | 参数4: | 参数5: | 参数6:
> 
> 我这边手机端发消息日志是 EventSendOutMsg ， 版本不一致吗？

对的，我用手机微信发消息给联系人，我在可爱猫的ihttp插件日志里面显示的是EventFriendMsg。因为可爱猫527识别的wxid并不是原始wxid，是修改过的wxid。我的微信号，比较老，刚注册的时候就修改过一次wxid，然后现在新政策是一年修改一次，我修改了，就导致有两个wxid，一个是原始的wxid就算注册的时候修改的那个，一个新的wxid。
正因为robot_wxid和from_wxid不一致，导致可爱猫认为是好友发来的消息。
可爱猫527，ihttp1.1.6.1

**Comment by phoenixxie0** [comment]
我尝试在@self.bot.on('EventFriendMsg')下面添加一个from_wxid的判定，这样似乎还能作为一个功能，来作为屏蔽某些联系人的消息的功能？。

**Comment by 0honus0** [comment]
> 我尝试在@self.bot.on('EventFriendMsg')下面添加一个from_wxid的判定，这样似乎还能作为一个功能，来作为屏蔽某些联系人的消息的功能？。

作为一个转发，没必要实现这样的功能，把这样的联系人绑定一个静音群组就好了

**Comment by 0honus0** [comment]
> > {"event":"EventSendOutMsg","robot_wxid":"wxid_0gojra8******2","robot_name":"","type":1,"from_wxid":"wxid_0gojra8******2","from_name":"","final_from_wxid":"wxid_0gojra8*_****2","final_from_name":"","to_wxid":"wxid_18wkxl0****_","msgid":"1064114996","msg":"不好搞"} | 参数2: | 参数3: | 参数4: | 参数5: | 参数6:
> > 我这边手机端发消息日志是 EventSendOutMsg ， 版本不一致吗？
> 
> 对的，我用手机微信发消息给联系人，我在可爱猫的ihttp插件日志里面显示的是EventFriendMsg。因为可爱猫527识别的wxid并不是原始wxid，是修改过的wxid。我的微信号，比较老，刚注册的时候就修改过一次wxid，然后现在新政策是一年修改一次，我修改了，就导致有两个wxid，一个是原始的wxid就算注册的时候修改的那个，一个新的wxid。 正因为robot_wxid和from_wxid不一致，导致可爱猫认为是好友发来的消息。 可爱猫527，ihttp1.1.6.1

那应该是可爱猫的bug

**Comment by phoenixxie0** [comment]
> > > {"event":"EventSendOutMsg","robot_wxid":"wxid_0gojra8******2","robot_name":"","type":1,"from_wxid":"wxid_0gojra8******2","from_name":"","final_from_wxid":"wxid_0gojra8*_****2","final_from_name":"","to_wxid":"wxid_18wkxl0****_","msgid":"1064114996","msg":"不好搞"} | 参数2: | 参数3: | 参数4: | 参数5: | 参数6:
> > > 我这边手机端发消息日志是 EventSendOutMsg ， 版本不一致吗？
> > 
> > 
> > 对的，我用手机微信发消息给联系人，我在可爱猫的ihttp插件日志里面显示的是EventFriendMsg。因为可爱猫527识别的wxid并不是原始wxid，是修改过的wxid。我的微信号，比较老，刚注册的时候就修改过一次wxid，然后现在新政策是一年修改一次，我修改了，就导致有两个wxid，一个是原始的wxid就算注册的时候修改的那个，一个新的wxid。 正因为robot_wxid和from_wxid不一致，导致可爱猫认为是好友发来的消息。 可爱猫527，ihttp1.1.6.1
> 
> 那应该是可爱猫的bug

是的，应该是可爱猫的bug。efb那边有一个efb_filter_middleware。在这里做个判断，修改以下那个中间件，就可以做成消息过滤。

**Comment by 0honus0** [comment]
不太想改了，把自己的消息绑定到一个群组加静音算了
