### ISSUE TITLE
更改Python名称

### ISSUE THREAD

**Issue by iaurman** [0honus0/efb-wechat-cutecat-slave#33]
**本项目**在pip中的名字`efb-wechat-slave`与**Web版**在pip中的名字一致，这会造成疑惑。

比如今天我想要升级pip所有包，但因为名称一样，pip认为本项目是旧的Web版本，并准备将本项目升级为Web版本。。。

```
$ pip list --outdated --user | grep efb-wechat-slave
efb-wechat-slave   0.1.2   2.0.7       wheel
```

本项目github名称为`efb-wechat-cutecat-slave`，为什么一开始不使用这个名称呢？

**Comment by 0honus0** [comment]
名字随便起的，因为没有项目依赖这个包，所以名字没特别修改，后继可以修改
